# Generated by Django 5.2.5 on 2025-08-29 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('seril_number', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('install_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=50)),
            ],
        ),
    ]
