# Generated by Django 5.2.5 on 2025-08-29 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_Add_Equipment_Model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('received', 'Received')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.sparepart')),
            ],
        ),
        migrations.CreateModel(
            name='SpareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('issue', 'Issue'), ('receive', 'Receive'), ('transfer', 'Transfer')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_requests', to=settings.AUTH_USER_MODEL)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='webpages.sparepart')),
            ],
        ),
    ]
