# Generated by Django 5.2.5 on 2025-08-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_Add_MaintWorkOrder_Model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_Type', models.CharField(choices=[('oee', 'OEE'), ('availability', 'Availability'), ('reliability', 'Reliability'), ('shutdown', 'Shutdown'), ('part_replacement', 'Part Replacement')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='webpages.equipment')),
            ],
        ),
    ]
